### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by shivam1423** [arya46/VQA_HieCoAtt#2]
I have performed the setup and given input image and question but when I click on generate answer it displays this error.
`Default MaxPoolingOp only supports NHWC on device type CPU [[node vgg19/block1_pool/MaxPool (defined at /home/shivam/Desktop/VQA-Flask-App/utils/helper_functions.py:30) ]] [Op:__inference_distributed_function_2303] Function call stack: distributed_function`

**Comment by arya46** [comment]
Hi @shivam1423 The meaning of NHWC is:
- N: number of images in the batch
- H: height of the image
- W: width of the image
- C: number of channels of the image
Please make sure your input is present in the above format.

There is a chance that your input is present as NCHW. Convert your input from the format NCHW to NHWC.
Let me know if that solves your problem.

**Comment by shivam1423** [comment]
Hello @arya46 so what exactly I have to change in the code?

**Comment by arya46** [comment]
@shivam1423 Try changing `K.set_image_data_format('channels_first')` to `K.set_image_data_format('channels_last')` in `utils/helper_fucntions.py`
If that still doesn't solve the problem, the reason could be a compatibility issue with Tensorflow.
Try to run the app with TF 2.1.0 (with the unmodified code)

**Comment by shivam1423** [comment]
@arya46 When I tried with `K.set_image_data_format('channels_last')` .
The main.py file gave an error `ValueError: Negative dimension size caused by subtracting 2 from 1 for 'block2_pool/MaxPool' (op: 'MaxPool') with input shapes: [?,1,112,128].`

**Comment by arya46** [comment]
@shivam1423 as expected, changing the `K.set_image_data_format()` breaks the codes in other parts.
Did you try with TF 2.1.0? The model was trained with version 2.1.0. It is quite common to face unwanted technical issues when you try to run the same with other TF versions.
I have not tried to run it with other versions.

**Comment by shivam1423** [comment]
Previously I was using TF 2.1.2. Now as you said to shift TF 2.1.0. Now the main.py file is giving an error.

Traceback (most recent call last):
  File "main.py", line 43, in <module>
    model = tf.keras.models.load_model(MODEL_PATH, custom_objects=custom_objects, compile=False)
  File "/home/shivam/Desktop/VQA-Flask-App/virtualenvironment/VQA/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/shivam/Desktop/VQA-Flask-App/virtualenvironment/VQA/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
Now what should I do?

**Comment by arya46** [comment]
@shivam1423 Above error suggests that `model_config` is a **str** datatype. Did you modify the code and declared `model_config` somewhere else? 
If no, please refer to the training notebooks [here](https://github.com/arya46/portfolio_notebooks/tree/master/Visual%20Question%20Answering) and train the model from scratch. 
I am not sure why you're facing the issue. Someone else used the same code somewhere around last month. It worked perfectly for him.
I would really appreciate it if you could figure out the issue and create a pull request. Thank you

**Comment by shivam1423** [comment]
@arya46  Thanks for sharing the scratch code. Can you just share me these 2 json file(vqa_raw_train2014.json vqa_raw_val2014.json) that is used in the VQA 3.ipynb file.

**Comment by arya46** [comment]
@shivam1423 Those files are generated by running the `process_question_annotation()` function. Execute the codes cell by cell. Everything that you need will be generated on the go.

**Comment by shivam1423** [comment]
@arya46 Thanks, I have trained the model succesfully for 60 epochs and generated 3 weight file(ckpt-12.data-00000-of-00002, ckpt-12.data-00001-of-00002, ckpt-12.index) in the training checkpoint folder. How do I get complete_model.h5 file? Also where have you used those weights?

**Comment by akashrajum7** [comment]
> 
> 
> Previously I was using TF 2.1.2. Now as you said to shift TF 2.1.0. Now the main.py file is giving an error.
> 
> Traceback (most recent call last):
> File "main.py", line 43, in
> model = tf.keras.models.load_model(MODEL_PATH, custom_objects=custom_objects, compile=False)
> File "/home/shivam/Desktop/VQA-Flask-App/virtualenvironment/VQA/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
> return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
> File "/home/shivam/Desktop/VQA-Flask-App/virtualenvironment/VQA/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
> model_config = json.loads(model_config.decode('utf-8'))
> AttributeError: 'str' object has no attribute 'decode'
> Now what should I do?

I was able to solve this issue by installing h5py version 2.10.0

**Comment by arya46** [comment]
@akashrajum7 Thank you for the update. I will update the h5py version in requirements.txt file.
