### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by Deepak3693** [arya46/VQA_HieCoAtt#3]
I have cloned all the files and executed the main.py file. Below is the error being received 
Shape must be at least rank 3 but is rank 2 for '{{node BiasAdd}} = BiasAdd[T=DT_FLOAT, data_format="NCHW"](add, BiasAdd/ReadVariableOp)' with input shapes: [?,2048], [2048].
@arya46

**Comment by arya46** [comment]
@Deepak3693 Use TF 2.1. Also, run the app with GPU.

**Comment by Devika2020** [comment]
It is asking me to sign in to local host. What the username and password?

**Comment by Devika2020** [comment]
Also can i run this without gpu?

**Comment by MrinalBanchhor** [comment]
It is showing error that "  [Errno 2] No such file or directory: 'static/m.jpg'  ". What should i do ?

**Comment by arya46** [comment]
@MrinalBanchhor The app first uploads the file to a folder named "static" before it can proceed with other steps. Make sure that your file is getting saved in the "static" folder.

**Comment by hirafs** [comment]
> It is showing error that " [Errno 2] No such file or directory: 'static/m.jpg' ". What should i do ?

I am facing the same issue. Any leads?

**Comment by arya46** [comment]
@hirafs Please make sure that you have a folder named 'static' in your project root. The logic tries to find the image that is saved in the static folder during prediction (the image is saved there when you upload the image). If the folder is not present, the saving of the file will not be complete, and you could face that error.

**Comment by arya46** [comment]
@Devika2020 Yes, both the train and inference is set to run on GPU.

**Comment by AbhimanyuSethi-98** [comment]
Hey! Can the inference be run without a GPU? If so, could you please help me how to go about it?
Thanks!

**Comment by arya46** [comment]
@AbhimanyuSethi-98 I have not tried that out. I would be glad if you can try doing that and let me know.
