### ISSUE TITLE
facing error

### ISSUE THREAD

**Issue by nishantmane7781** [arya46/VQA_HieCoAtt#7]
tf.config.experimental.set_memory_growth(physical_devices[0], True)
IndexError: list index out of range

I do not understand it why this error coming

**Comment by arya46** [comment]
@vikrantmane7781 It suggests that TF is unable to load your GPU.

We have defined `physical_devices = tf.config.list_physical_devices('GPU')`
If GPU is not enabled, `physical_devices` will be an empty list, and hence you get an `"IndexError"` error when you try to access 0th index (`physical_devices[0]`).
